version: '3.8'
services:
  app:
    container_name: springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mypostgresdb
    restart: on-failure

  mypostgresdb:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog-docker